name: "Bump"

on:
  workflow_run:
    workflows:
      - "Publish"
    types:
      - completed
    branches:
      - "master"
      - "master-2"
      - "master-beta"

concurrency:
  group: bump-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

jobs:
  bump:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "Bump Version"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
          token: ${{ github.token }}

      - name: "Bump version"
        uses: phips28/gh-action-bump-version@v11.0.7
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          default: "${{ (github.event.workflow_run.head_branch == 'master-2' || github.event.workflow_run.head_branch == 'master-beta') && 'prerelease' || 'minor' }}"
          preid: "${{ github.event.workflow_run.head_branch == 'master-2' && 'alpha' || (github.event.workflow_run.head_branch == 'master-beta' && 'beta' || '') }}"
          tag-prefix: "release-"
          bump-policy: last-commit
          check-last-commit-only: true
          target-branch: ${{ github.event.workflow_run.head_branch }}
          commit-message: "ci: version bump to v{{version}} [skip ci]"
